#!/bin/bash

# poweroff the computer after the currently played thing finished

# for now, we only check MPD. this may change in the future
# also, we crop the playlist, because otherwise next song may start (crossover)
mpc single on && mpc current --wait && sudo poweroff
