#!/bin/bash
# Author: Philipp Moers <soziflip gmail com>
# This script disables an xinput device if it is enabled and vice versa


if [ -n "$1" ]; then
    DEVICE=$1
else
    # DEVICE="FocalTechPS/2 FocalTech FocalTech Touchpad"
    DEVICE=`xinput list --name-only | grep -i touchpad`
fi


#DEVICE="PS/2 Logitech Wheel Mouse"
#DEVICE="PS/2 FocalTech FocalTech Touchpad in mouse emulation mode"


# ---------------------------------------------------------------------

# get old state
STATE=$(xinput --list-props "$DEVICE" | grep "Device Enabled" | cut -f3)

# calculate next state
if [ $STATE -eq 1 ]; then
    NEXTSTATE=0
else
    NEXTSTATE=1
fi

# set next state
xinput --set-prop "$DEVICE" "Device Enabled" $NEXTSTATE

